---
mode: matcher
log_level: debug
introspection_addr: ":8089"
http_listen_addr: ":80"
matcher:
  indexer_addr: http://indexer/
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  max_conn_pool: 100
  migrations: true
# tracing and metrics config
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "jaeger:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
