version: '2'

services:
  auth:
    image: cesanta/docker_auth:stable
    ports:
      - "5001:5001"
    volumes:
      - ./auth_server/config:/config:ro
      - ./auth_server/ssl:/ssl
    command: --v=2 --alsologtostderr /config/auth_config.yml
    container_name: "auth"

  registry:
    image: registry:2.2.1
    ports:
      - 5000:5000
    volumes:
      - ./auth_server/ssl:/ssl
      - registry-data:/var/lib/registry
    container_name: "registry"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://auth:5001/auth
      - REGISTRY_AUTH_TOKEN_SERVICE="registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="auth_service"
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem

  clair:
    image: quay.io/coreos/clair:v1.0.0-rc1
    volumes:
      - /tmp:/tmp
      - ./config:/config
      - clair-data:/var/local
    ports:
      - 6060:6060
      - 6061:6061
    container_name: "clair"
    command: --log-level=debug --config=/config/clair.yml

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=root

volumes:
  clair-data:
    driver: local
  registry-data:
    driver: local
